export const CONFIG = {
  BASE_API_URL: import.meta.env.VITE_BASE_API_URL,
  ENCRYPTION_TOKEN: import.meta.env.VITE_ENCRYPTION_TOKEN,
  AUTH_LOGIN_ENDPOINT: import.meta.env.VITE_AUTH_LOGIN_ENDPOINT,
  AUTH_LOGOUT_ENDPOINT: import.meta.env.VITE_AUTH_LOGOUT_ENDPOINT,
  AUTH_PROFILE_ENDPOINT: import.meta.env.VITE_AUTH_PROFILE_ENDPOINT,
};
