/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedServicesIndexRouteImport } from './routes/_protected/services/index'
import { Route as ProtectedReportsIndexRouteImport } from './routes/_protected/reports/index'
import { Route as ProtectedNotificationsIndexRouteImport } from './routes/_protected/notifications/index'
import { Route as ProtectedGroupsIndexRouteImport } from './routes/_protected/groups/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicAuthUnderdevelopmentRouteImport } from './routes/_public/auth/underdevelopment'
import { Route as PublicAuthUnauthorizedRouteImport } from './routes/_public/auth/unauthorized'
import { Route as PublicAuthResetpasswordRouteImport } from './routes/_public/auth/resetpassword'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as ProtectedServicesCreateRouteImport } from './routes/_protected/services/create'
import { Route as ProtectedServicesUuidRouteImport } from './routes/_protected/services/$uuid'
import { Route as ProtectedLogsUptimelogsRouteImport } from './routes/_protected/logs/uptimelogs'
import { Route as ProtectedLogsSsllogsRouteImport } from './routes/_protected/logs/ssllogs'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesIndexRoute = ProtectedServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsIndexRoute = ProtectedReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificationsIndexRoute =
  ProtectedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedGroupsIndexRoute = ProtectedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthUnderdevelopmentRoute =
  PublicAuthUnderdevelopmentRouteImport.update({
    id: '/_public/auth/underdevelopment',
    path: '/auth/underdevelopment',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicAuthUnauthorizedRoute = PublicAuthUnauthorizedRouteImport.update({
  id: '/_public/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthResetpasswordRoute = PublicAuthResetpasswordRouteImport.update({
  id: '/_public/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/_public/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedServicesCreateRoute = ProtectedServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesUuidRoute = ProtectedServicesUuidRouteImport.update({
  id: '/services/$uuid',
  path: '/services/$uuid',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLogsUptimelogsRoute = ProtectedLogsUptimelogsRouteImport.update({
  id: '/logs/uptimelogs',
  path: '/logs/uptimelogs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLogsSsllogsRoute = ProtectedLogsSsllogsRouteImport.update({
  id: '/logs/ssllogs',
  path: '/logs/ssllogs',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs/ssllogs': typeof ProtectedLogsSsllogsRoute
  '/logs/uptimelogs': typeof ProtectedLogsUptimelogsRoute
  '/services/$uuid': typeof ProtectedServicesUuidRoute
  '/services/create': typeof ProtectedServicesCreateRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/resetpassword': typeof PublicAuthResetpasswordRoute
  '/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/auth/underdevelopment': typeof PublicAuthUnderdevelopmentRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/groups': typeof ProtectedGroupsIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/services': typeof ProtectedServicesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs/ssllogs': typeof ProtectedLogsSsllogsRoute
  '/logs/uptimelogs': typeof ProtectedLogsUptimelogsRoute
  '/services/$uuid': typeof ProtectedServicesUuidRoute
  '/services/create': typeof ProtectedServicesCreateRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/resetpassword': typeof PublicAuthResetpasswordRoute
  '/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/auth/underdevelopment': typeof PublicAuthUnderdevelopmentRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/groups': typeof ProtectedGroupsIndexRoute
  '/notifications': typeof ProtectedNotificationsIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/services': typeof ProtectedServicesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/logs/ssllogs': typeof ProtectedLogsSsllogsRoute
  '/_protected/logs/uptimelogs': typeof ProtectedLogsUptimelogsRoute
  '/_protected/services/$uuid': typeof ProtectedServicesUuidRoute
  '/_protected/services/create': typeof ProtectedServicesCreateRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/resetpassword': typeof PublicAuthResetpasswordRoute
  '/_public/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/_public/auth/underdevelopment': typeof PublicAuthUnderdevelopmentRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/groups/': typeof ProtectedGroupsIndexRoute
  '/_protected/notifications/': typeof ProtectedNotificationsIndexRoute
  '/_protected/reports/': typeof ProtectedReportsIndexRoute
  '/_protected/services/': typeof ProtectedServicesIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs/ssllogs'
    | '/logs/uptimelogs'
    | '/services/$uuid'
    | '/services/create'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/auth/unauthorized'
    | '/auth/underdevelopment'
    | '/dashboard'
    | '/groups'
    | '/notifications'
    | '/reports'
    | '/services'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs/ssllogs'
    | '/logs/uptimelogs'
    | '/services/$uuid'
    | '/services/create'
    | '/auth/login'
    | '/auth/resetpassword'
    | '/auth/unauthorized'
    | '/auth/underdevelopment'
    | '/dashboard'
    | '/groups'
    | '/notifications'
    | '/reports'
    | '/services'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/logs/ssllogs'
    | '/_protected/logs/uptimelogs'
    | '/_protected/services/$uuid'
    | '/_protected/services/create'
    | '/_public/auth/login'
    | '/_public/auth/resetpassword'
    | '/_public/auth/unauthorized'
    | '/_public/auth/underdevelopment'
    | '/_protected/dashboard/'
    | '/_protected/groups/'
    | '/_protected/notifications/'
    | '/_protected/reports/'
    | '/_protected/services/'
    | '/_protected/settings/'
    | '/_protected/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthResetpasswordRoute: typeof PublicAuthResetpasswordRoute
  PublicAuthUnauthorizedRoute: typeof PublicAuthUnauthorizedRoute
  PublicAuthUnderdevelopmentRoute: typeof PublicAuthUnderdevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services/': {
      id: '/_protected/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ProtectedServicesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/': {
      id: '/_protected/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notifications/': {
      id: '/_protected/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/groups/': {
      id: '/_protected/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof ProtectedGroupsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/underdevelopment': {
      id: '/_public/auth/underdevelopment'
      path: '/auth/underdevelopment'
      fullPath: '/auth/underdevelopment'
      preLoaderRoute: typeof PublicAuthUnderdevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/unauthorized': {
      id: '/_public/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof PublicAuthUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/resetpassword': {
      id: '/_public/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof PublicAuthResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/services/create': {
      id: '/_protected/services/create'
      path: '/services/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof ProtectedServicesCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services/$uuid': {
      id: '/_protected/services/$uuid'
      path: '/services/$uuid'
      fullPath: '/services/$uuid'
      preLoaderRoute: typeof ProtectedServicesUuidRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logs/uptimelogs': {
      id: '/_protected/logs/uptimelogs'
      path: '/logs/uptimelogs'
      fullPath: '/logs/uptimelogs'
      preLoaderRoute: typeof ProtectedLogsUptimelogsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logs/ssllogs': {
      id: '/_protected/logs/ssllogs'
      path: '/logs/ssllogs'
      fullPath: '/logs/ssllogs'
      preLoaderRoute: typeof ProtectedLogsSsllogsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedLogsSsllogsRoute: typeof ProtectedLogsSsllogsRoute
  ProtectedLogsUptimelogsRoute: typeof ProtectedLogsUptimelogsRoute
  ProtectedServicesUuidRoute: typeof ProtectedServicesUuidRoute
  ProtectedServicesCreateRoute: typeof ProtectedServicesCreateRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedGroupsIndexRoute: typeof ProtectedGroupsIndexRoute
  ProtectedNotificationsIndexRoute: typeof ProtectedNotificationsIndexRoute
  ProtectedReportsIndexRoute: typeof ProtectedReportsIndexRoute
  ProtectedServicesIndexRoute: typeof ProtectedServicesIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLogsSsllogsRoute: ProtectedLogsSsllogsRoute,
  ProtectedLogsUptimelogsRoute: ProtectedLogsUptimelogsRoute,
  ProtectedServicesUuidRoute: ProtectedServicesUuidRoute,
  ProtectedServicesCreateRoute: ProtectedServicesCreateRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedGroupsIndexRoute: ProtectedGroupsIndexRoute,
  ProtectedNotificationsIndexRoute: ProtectedNotificationsIndexRoute,
  ProtectedReportsIndexRoute: ProtectedReportsIndexRoute,
  ProtectedServicesIndexRoute: ProtectedServicesIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthResetpasswordRoute: PublicAuthResetpasswordRoute,
  PublicAuthUnauthorizedRoute: PublicAuthUnauthorizedRoute,
  PublicAuthUnderdevelopmentRoute: PublicAuthUnderdevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
