/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSharedRouteImport } from './routes/_protected/_shared'
import { Route as ProtectedOperatorRouteImport } from './routes/_protected/_operator'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/_admin'
import { Route as ProtectedServicesIndexRouteImport } from './routes/_protected/services/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicAuthUnauthorizedRouteImport } from './routes/_public/auth/unauthorized'
import { Route as PublicAuthSetPasswordRouteImport } from './routes/_public/auth/set-password'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/auth/reset-password'
import { Route as PublicAuthRequestPasswordRouteImport } from './routes/_public/auth/request-password'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as ProtectedUserProfileRouteImport } from './routes/_protected/user/profile'
import { Route as ProtectedServicesUuidRouteImport } from './routes/_protected/services/$uuid'
import { Route as ProtectedReportsUptimeReportsRouteImport } from './routes/_protected/reports/uptime-reports'
import { Route as ProtectedReportsSslReportsRouteImport } from './routes/_protected/reports/ssl-reports'
import { Route as ProtectedAdminNotificationHistoryRouteImport } from './routes/_protected/_admin/notification-history'
import { Route as ProtectedAdminAuditLogsRouteImport } from './routes/_protected/_admin/audit-logs'
import { Route as ProtectedAdminUsersIndexRouteImport } from './routes/_protected/_admin/users/index'
import { Route as ProtectedAdminTemplatesIndexRouteImport } from './routes/_protected/_admin/templates/index'
import { Route as ProtectedAdminSettingsIndexRouteImport } from './routes/_protected/_admin/settings/index'
import { Route as ProtectedAdminNotificationsIndexRouteImport } from './routes/_protected/_admin/notifications/index'
import { Route as ProtectedAdminGroupsIndexRouteImport } from './routes/_protected/_admin/groups/index'
import { Route as ProtectedSharedServicesCreateRouteImport } from './routes/_protected/_shared/services/create'
import { Route as ProtectedAdminUsersCreateUserRouteImport } from './routes/_protected/_admin/users/create-user'
import { Route as ProtectedAdminTemplatesUuidRouteImport } from './routes/_protected/_admin/templates/$uuid'
import { Route as ProtectedAdminGroupsUuidRouteImport } from './routes/_protected/_admin/groups/$uuid'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSharedRoute = ProtectedSharedRouteImport.update({
  id: '/_shared',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOperatorRoute = ProtectedOperatorRouteImport.update({
  id: '/_operator',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesIndexRoute = ProtectedServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthUnauthorizedRoute = PublicAuthUnauthorizedRouteImport.update({
  id: '/auth/unauthorized',
  path: '/auth/unauthorized',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthSetPasswordRoute = PublicAuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRequestPasswordRoute =
  PublicAuthRequestPasswordRouteImport.update({
    id: '/auth/request-password',
    path: '/auth/request-password',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedUserProfileRoute = ProtectedUserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServicesUuidRoute = ProtectedServicesUuidRouteImport.update({
  id: '/services/$uuid',
  path: '/services/$uuid',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsUptimeReportsRoute =
  ProtectedReportsUptimeReportsRouteImport.update({
    id: '/reports/uptime-reports',
    path: '/reports/uptime-reports',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsSslReportsRoute =
  ProtectedReportsSslReportsRouteImport.update({
    id: '/reports/ssl-reports',
    path: '/reports/ssl-reports',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminNotificationHistoryRoute =
  ProtectedAdminNotificationHistoryRouteImport.update({
    id: '/notification-history',
    path: '/notification-history',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminAuditLogsRoute = ProtectedAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminUsersIndexRoute =
  ProtectedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminTemplatesIndexRoute =
  ProtectedAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminSettingsIndexRoute =
  ProtectedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminNotificationsIndexRoute =
  ProtectedAdminNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminGroupsIndexRoute =
  ProtectedAdminGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedSharedServicesCreateRoute =
  ProtectedSharedServicesCreateRouteImport.update({
    id: '/services/create',
    path: '/services/create',
    getParentRoute: () => ProtectedSharedRoute,
  } as any)
const ProtectedAdminUsersCreateUserRoute =
  ProtectedAdminUsersCreateUserRouteImport.update({
    id: '/users/create-user',
    path: '/users/create-user',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminTemplatesUuidRoute =
  ProtectedAdminTemplatesUuidRouteImport.update({
    id: '/templates/$uuid',
    path: '/templates/$uuid',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminGroupsUuidRoute =
  ProtectedAdminGroupsUuidRouteImport.update({
    id: '/groups/$uuid',
    path: '/groups/$uuid',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof ProtectedAdminAuditLogsRoute
  '/notification-history': typeof ProtectedAdminNotificationHistoryRoute
  '/reports/ssl-reports': typeof ProtectedReportsSslReportsRoute
  '/reports/uptime-reports': typeof ProtectedReportsUptimeReportsRoute
  '/services/$uuid': typeof ProtectedServicesUuidRoute
  '/user/profile': typeof ProtectedUserProfileRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/request-password': typeof PublicAuthRequestPasswordRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/auth/set-password': typeof PublicAuthSetPasswordRoute
  '/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/services': typeof ProtectedServicesIndexRoute
  '/groups/$uuid': typeof ProtectedAdminGroupsUuidRoute
  '/templates/$uuid': typeof ProtectedAdminTemplatesUuidRoute
  '/users/create-user': typeof ProtectedAdminUsersCreateUserRoute
  '/services/create': typeof ProtectedSharedServicesCreateRoute
  '/groups': typeof ProtectedAdminGroupsIndexRoute
  '/notifications': typeof ProtectedAdminNotificationsIndexRoute
  '/settings': typeof ProtectedAdminSettingsIndexRoute
  '/templates': typeof ProtectedAdminTemplatesIndexRoute
  '/users': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof ProtectedAdminAuditLogsRoute
  '/notification-history': typeof ProtectedAdminNotificationHistoryRoute
  '/reports/ssl-reports': typeof ProtectedReportsSslReportsRoute
  '/reports/uptime-reports': typeof ProtectedReportsUptimeReportsRoute
  '/services/$uuid': typeof ProtectedServicesUuidRoute
  '/user/profile': typeof ProtectedUserProfileRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/request-password': typeof PublicAuthRequestPasswordRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/auth/set-password': typeof PublicAuthSetPasswordRoute
  '/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/services': typeof ProtectedServicesIndexRoute
  '/groups/$uuid': typeof ProtectedAdminGroupsUuidRoute
  '/templates/$uuid': typeof ProtectedAdminTemplatesUuidRoute
  '/users/create-user': typeof ProtectedAdminUsersCreateUserRoute
  '/services/create': typeof ProtectedSharedServicesCreateRoute
  '/groups': typeof ProtectedAdminGroupsIndexRoute
  '/notifications': typeof ProtectedAdminNotificationsIndexRoute
  '/settings': typeof ProtectedAdminSettingsIndexRoute
  '/templates': typeof ProtectedAdminTemplatesIndexRoute
  '/users': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/_admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/_operator': typeof ProtectedOperatorRoute
  '/_protected/_shared': typeof ProtectedSharedRouteWithChildren
  '/_protected/_admin/audit-logs': typeof ProtectedAdminAuditLogsRoute
  '/_protected/_admin/notification-history': typeof ProtectedAdminNotificationHistoryRoute
  '/_protected/reports/ssl-reports': typeof ProtectedReportsSslReportsRoute
  '/_protected/reports/uptime-reports': typeof ProtectedReportsUptimeReportsRoute
  '/_protected/services/$uuid': typeof ProtectedServicesUuidRoute
  '/_protected/user/profile': typeof ProtectedUserProfileRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/request-password': typeof PublicAuthRequestPasswordRoute
  '/_public/auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/auth/set-password': typeof PublicAuthSetPasswordRoute
  '/_public/auth/unauthorized': typeof PublicAuthUnauthorizedRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/services/': typeof ProtectedServicesIndexRoute
  '/_protected/_admin/groups/$uuid': typeof ProtectedAdminGroupsUuidRoute
  '/_protected/_admin/templates/$uuid': typeof ProtectedAdminTemplatesUuidRoute
  '/_protected/_admin/users/create-user': typeof ProtectedAdminUsersCreateUserRoute
  '/_protected/_shared/services/create': typeof ProtectedSharedServicesCreateRoute
  '/_protected/_admin/groups/': typeof ProtectedAdminGroupsIndexRoute
  '/_protected/_admin/notifications/': typeof ProtectedAdminNotificationsIndexRoute
  '/_protected/_admin/settings/': typeof ProtectedAdminSettingsIndexRoute
  '/_protected/_admin/templates/': typeof ProtectedAdminTemplatesIndexRoute
  '/_protected/_admin/users/': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/notification-history'
    | '/reports/ssl-reports'
    | '/reports/uptime-reports'
    | '/services/$uuid'
    | '/user/profile'
    | '/auth/login'
    | '/auth/register'
    | '/auth/request-password'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/unauthorized'
    | '/dashboard'
    | '/services'
    | '/groups/$uuid'
    | '/templates/$uuid'
    | '/users/create-user'
    | '/services/create'
    | '/groups'
    | '/notifications'
    | '/settings'
    | '/templates'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/notification-history'
    | '/reports/ssl-reports'
    | '/reports/uptime-reports'
    | '/services/$uuid'
    | '/user/profile'
    | '/auth/login'
    | '/auth/register'
    | '/auth/request-password'
    | '/auth/reset-password'
    | '/auth/set-password'
    | '/auth/unauthorized'
    | '/dashboard'
    | '/services'
    | '/groups/$uuid'
    | '/templates/$uuid'
    | '/users/create-user'
    | '/services/create'
    | '/groups'
    | '/notifications'
    | '/settings'
    | '/templates'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/_admin'
    | '/_protected/_operator'
    | '/_protected/_shared'
    | '/_protected/_admin/audit-logs'
    | '/_protected/_admin/notification-history'
    | '/_protected/reports/ssl-reports'
    | '/_protected/reports/uptime-reports'
    | '/_protected/services/$uuid'
    | '/_protected/user/profile'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/auth/request-password'
    | '/_public/auth/reset-password'
    | '/_public/auth/set-password'
    | '/_public/auth/unauthorized'
    | '/_protected/dashboard/'
    | '/_protected/services/'
    | '/_protected/_admin/groups/$uuid'
    | '/_protected/_admin/templates/$uuid'
    | '/_protected/_admin/users/create-user'
    | '/_protected/_shared/services/create'
    | '/_protected/_admin/groups/'
    | '/_protected/_admin/notifications/'
    | '/_protected/_admin/settings/'
    | '/_protected/_admin/templates/'
    | '/_protected/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_shared': {
      id: '/_protected/_shared'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedSharedRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_operator': {
      id: '/_protected/_operator'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedOperatorRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin': {
      id: '/_protected/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services/': {
      id: '/_protected/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ProtectedServicesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/unauthorized': {
      id: '/_public/auth/unauthorized'
      path: '/auth/unauthorized'
      fullPath: '/auth/unauthorized'
      preLoaderRoute: typeof PublicAuthUnauthorizedRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/set-password': {
      id: '/_public/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof PublicAuthSetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password': {
      id: '/_public/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/request-password': {
      id: '/_public/auth/request-password'
      path: '/auth/request-password'
      fullPath: '/auth/request-password'
      preLoaderRoute: typeof PublicAuthRequestPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/user/profile': {
      id: '/_protected/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof ProtectedUserProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/services/$uuid': {
      id: '/_protected/services/$uuid'
      path: '/services/$uuid'
      fullPath: '/services/$uuid'
      preLoaderRoute: typeof ProtectedServicesUuidRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/uptime-reports': {
      id: '/_protected/reports/uptime-reports'
      path: '/reports/uptime-reports'
      fullPath: '/reports/uptime-reports'
      preLoaderRoute: typeof ProtectedReportsUptimeReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/ssl-reports': {
      id: '/_protected/reports/ssl-reports'
      path: '/reports/ssl-reports'
      fullPath: '/reports/ssl-reports'
      preLoaderRoute: typeof ProtectedReportsSslReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_admin/notification-history': {
      id: '/_protected/_admin/notification-history'
      path: '/notification-history'
      fullPath: '/notification-history'
      preLoaderRoute: typeof ProtectedAdminNotificationHistoryRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/audit-logs': {
      id: '/_protected/_admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof ProtectedAdminAuditLogsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/users/': {
      id: '/_protected/_admin/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/templates/': {
      id: '/_protected/_admin/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ProtectedAdminTemplatesIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/settings/': {
      id: '/_protected/_admin/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/notifications/': {
      id: '/_protected/_admin/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedAdminNotificationsIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/groups/': {
      id: '/_protected/_admin/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof ProtectedAdminGroupsIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_shared/services/create': {
      id: '/_protected/_shared/services/create'
      path: '/services/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof ProtectedSharedServicesCreateRouteImport
      parentRoute: typeof ProtectedSharedRoute
    }
    '/_protected/_admin/users/create-user': {
      id: '/_protected/_admin/users/create-user'
      path: '/users/create-user'
      fullPath: '/users/create-user'
      preLoaderRoute: typeof ProtectedAdminUsersCreateUserRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/templates/$uuid': {
      id: '/_protected/_admin/templates/$uuid'
      path: '/templates/$uuid'
      fullPath: '/templates/$uuid'
      preLoaderRoute: typeof ProtectedAdminTemplatesUuidRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_admin/groups/$uuid': {
      id: '/_protected/_admin/groups/$uuid'
      path: '/groups/$uuid'
      fullPath: '/groups/$uuid'
      preLoaderRoute: typeof ProtectedAdminGroupsUuidRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminAuditLogsRoute: typeof ProtectedAdminAuditLogsRoute
  ProtectedAdminNotificationHistoryRoute: typeof ProtectedAdminNotificationHistoryRoute
  ProtectedAdminGroupsUuidRoute: typeof ProtectedAdminGroupsUuidRoute
  ProtectedAdminTemplatesUuidRoute: typeof ProtectedAdminTemplatesUuidRoute
  ProtectedAdminUsersCreateUserRoute: typeof ProtectedAdminUsersCreateUserRoute
  ProtectedAdminGroupsIndexRoute: typeof ProtectedAdminGroupsIndexRoute
  ProtectedAdminNotificationsIndexRoute: typeof ProtectedAdminNotificationsIndexRoute
  ProtectedAdminSettingsIndexRoute: typeof ProtectedAdminSettingsIndexRoute
  ProtectedAdminTemplatesIndexRoute: typeof ProtectedAdminTemplatesIndexRoute
  ProtectedAdminUsersIndexRoute: typeof ProtectedAdminUsersIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminAuditLogsRoute: ProtectedAdminAuditLogsRoute,
  ProtectedAdminNotificationHistoryRoute:
    ProtectedAdminNotificationHistoryRoute,
  ProtectedAdminGroupsUuidRoute: ProtectedAdminGroupsUuidRoute,
  ProtectedAdminTemplatesUuidRoute: ProtectedAdminTemplatesUuidRoute,
  ProtectedAdminUsersCreateUserRoute: ProtectedAdminUsersCreateUserRoute,
  ProtectedAdminGroupsIndexRoute: ProtectedAdminGroupsIndexRoute,
  ProtectedAdminNotificationsIndexRoute: ProtectedAdminNotificationsIndexRoute,
  ProtectedAdminSettingsIndexRoute: ProtectedAdminSettingsIndexRoute,
  ProtectedAdminTemplatesIndexRoute: ProtectedAdminTemplatesIndexRoute,
  ProtectedAdminUsersIndexRoute: ProtectedAdminUsersIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedSharedRouteChildren {
  ProtectedSharedServicesCreateRoute: typeof ProtectedSharedServicesCreateRoute
}

const ProtectedSharedRouteChildren: ProtectedSharedRouteChildren = {
  ProtectedSharedServicesCreateRoute: ProtectedSharedServicesCreateRoute,
}

const ProtectedSharedRouteWithChildren = ProtectedSharedRoute._addFileChildren(
  ProtectedSharedRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedOperatorRoute: typeof ProtectedOperatorRoute
  ProtectedSharedRoute: typeof ProtectedSharedRouteWithChildren
  ProtectedReportsSslReportsRoute: typeof ProtectedReportsSslReportsRoute
  ProtectedReportsUptimeReportsRoute: typeof ProtectedReportsUptimeReportsRoute
  ProtectedServicesUuidRoute: typeof ProtectedServicesUuidRoute
  ProtectedUserProfileRoute: typeof ProtectedUserProfileRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedServicesIndexRoute: typeof ProtectedServicesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedOperatorRoute: ProtectedOperatorRoute,
  ProtectedSharedRoute: ProtectedSharedRouteWithChildren,
  ProtectedReportsSslReportsRoute: ProtectedReportsSslReportsRoute,
  ProtectedReportsUptimeReportsRoute: ProtectedReportsUptimeReportsRoute,
  ProtectedServicesUuidRoute: ProtectedServicesUuidRoute,
  ProtectedUserProfileRoute: ProtectedUserProfileRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedServicesIndexRoute: ProtectedServicesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthRequestPasswordRoute: typeof PublicAuthRequestPasswordRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
  PublicAuthSetPasswordRoute: typeof PublicAuthSetPasswordRoute
  PublicAuthUnauthorizedRoute: typeof PublicAuthUnauthorizedRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthRequestPasswordRoute: PublicAuthRequestPasswordRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
  PublicAuthSetPasswordRoute: PublicAuthSetPasswordRoute,
  PublicAuthUnauthorizedRoute: PublicAuthUnauthorizedRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
